### ISSUE TITLE
pipeline for view-limits

### ISSUE THREAD

**Issue by aappling-usgs** [USGS-VIZLAB/vizstorm#7]
View limits are defined as bounding coordinates in viz.yaml and formatted in fetch.view_limits. They potentially differ between mobile and desktop formats. They directly determine the spatial scope for geographical data, the storm track, and the plot; from there, precip and possibly gages (?) are clipped to the geographical bounds.

- Copy over `fetch.view_limits` and ensure that its helper functions (from scripts/visualize/plotting_utils.R in Maria) are available.
- Add comments to the `fetch.view_limits` code explaining what the function does and why
- Follow up on the existing comment "it would be nice to just use defaults if these aren't included" at https://github.com/USGS-VIZLAB/hurricane-maria/blob/master/scripts/fetch/fetch.view_limits.R#L11
- Is it possible that view-limits should also include or produce a list of states, e.g. as used in fetch.nws_conversion at https://github.com/USGS-VIZLAB/hurricane-maria/blob/master/scripts/fetch/fetch.nws_conversion.R#L5?

**Comment by jordansread** [comment]
I am wondering about the return type of `viewbox_limits`. 

is it useful to have it give you the `xlim` and `ylim`? Are these more useful than an `sp` or `sf` polygon box that would also include the `crs` used to build it? That way it also requires fewer conversions to 1) subset what features are either in it or partially in it, 2) plot it. 

So, I am proposing we return `sf::st_sfc` polygon. *or* we get a little fancier and return a `vizbox` class that is `sf::st_sfc` and inherits those methods, but also has a slot for some additional metadata, like the width and the height of the viewbox in graphics (svg) units.

**Comment by aappling-usgs** [comment]
I think `vizbox` or similar sounds good. You're considering @dblodgett-usgs 's use case from this morning in your calculations, right? https://github.com/dblodgett-usgs/uswb-viz/commit/a2bf16067496e9f62912cdb79a2a7a88f0890b12. Involves width, height, and pointsize...I confess to not knowing whether these are in svg units or not.

Up to you whether you think it's worth the coding to formalize `vizbox` as a class - sounds fine, just that my first thought would have just been an unclassed list that includes an `sf:st_sfc` within it if this is going to live in `vizstorm`. Or is this idea general enough - bounding coordinates and other info that determine the scaling of an svg - that it should live in `vizlab` proper and get a little extra formality because it'll be reused in a variety of ways?

**Comment by jordansread** [comment]
Another thought - 

what are the useful "defaults" for the height and width of the plotting area? I had assumed those would be defaults from the function that creates the svg viewbox, but are better defaults the actual dimension/aspect of the box given by the bbox after it is transformed by the crs?

**Comment by jordansread** [comment]
Yes, I saw blodgett's comments, but thought since we are rebuilding most of these functions back up from basics, we could re-assess if that is the place to be including those arguments. I will think about it a bit more.

**Comment by dblodgett-usgs** [comment]
Regarding the use of width/height/pointsize, I was just reusing what was in Maria. After fiddling with that, it became clear that an aspect ratio mismatch between the bbox and width/height was very annoying to figure out. I like the idea of not requiring the width/height.

However, we should leave it as an option as is in there now. In the case you want more content outside the bbox, you should be able to specify a larger width/height than would be indicated by the bbox aspect ratio.
